### PR TITLE
Update mainTrunk.m

### PR DESCRIPTION
**Pull request by Plswearpants**

### CODE REVIEW

**Review by m-altthaler — CHANGES_REQUESTED** [review]
The format is not up to the new standard

**Comment by Plswearpants** [comment]
Made a modification according to Markus's comments.

**Comment by Plswearpants** [comment]
VS01A block is split into two separating blocks: PA02A and VS01A, the first being the average to mask and the second being the plotting. The function is also updated to avgMaskFast, and the old function gridAvgMaskFast is deleted.

**Review by rysagree — APPROVED** [review]

**Comment by Plswearpants** [comment]
took jisun out from the requested reviewer

**Comment by m-altthaler** [comment]
This is resolve din #145

**Pull request closed without merging**
